server:
  port: 8081
spring:
  profiles:
    active: rewritepath_route

---
spring:
  cloud:
    gateway:
      routes:
      - id: cookie_route
        uri: http://httpbin.org:80/get
        predicates:
        - Cookie=name, forezp
  profiles: cookie_route

---
spring:
  cloud:
    gateway:
      routes:
      - id: method_route
        uri: http://httpbin.org:80/get
        predicates:
        - Method=GET         # 指定请求的方式为GET 如果是POST请求则会报错
  profiles: method_route

---
spring:
  cloud:
    gateway:
      routes:
      - id: path_route
        uri: http://httpbin.org:80/get
        predicates:
        - Path=/foo/{segment}  # 指定请求地址需要为 /foo/*
  profiles: path_route


---
spring:
  cloud:
    gateway:
      routes:
      - id: query_route
        uri: http://httpbin.org:80/get
        predicates:
        - Query=foo, ba.       # 指定请求参数为foo=ba.
  profiles: query_route


# 下面的配置中，所有的/foo/**开始的路径都会命中配置的router,并执行过滤器的逻辑，
# 然后转发到 https://blog.csdn.net，比如在页面上请求 localhost:8081/foo/forezp
# 此时会将请求转发到 https://blog.csdn.net/forezp的页面，若在网页上请求 localhost:8081/foo/forezp、1
# 页面显示404，因为不存在 https://blog.csdn.net/forezp/1 这个页面
---
spring:
  cloud:
    gateway:
      routes:
      - id: rewritepath_route
        uri: https://blog.csdn.net
        predicates:
        - Path=/foo/**
        filters:
        - RewritePath=/foo/(?<segment>.*), /$\{segment}
  profiles: rewritepath_route