eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8988

spring:
  zipkin:
    base-url: http://localhost:9411   # 配置倒链路服务器中

  application:
    name: service-hi